services:
  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    depends_on:
      - backend
    networks:
      - app-network
    environment:
      - VITE_API_URL=http://localhost:5174/api
    restart: "no"

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "5174:3000"
    environment:
      - NODE_ENV=production
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=secret
      - DB_NAME=pelisdb
      - PORT=3000
    depends_on:
      - mysql
    networks:
      - app-network
    restart: "no"

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=pelisdb
    volumes:
      - mysql_data:/var/lib/mysql
      - ./Backend/db/database.sql:/docker-entrypoint-initdb.d/database.sql
    networks:
      - app-network
    restart: "no"

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data: 